name: Test
on: 
  push:
jobs:
  test-job:
    runs-on: ubuntu-latest
    services: 
      test-emulator:
        image: ghcr.io/aertje/cloud-tasks-emulator:latest
        ports: 
          - 8123:8123
        options: >-
          --entrypoint "./emulator"
    steps:
      - name: Show pwd
        run: pwd
